/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Browse Listings */
        get: operations["browse_listings_listings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listings/{listing_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Listing */
        get: operations["get_listing_listings__listing_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listings/{listing_id}/similar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Similar Listings */
        get: operations["similar_listings_listings__listing_id__similar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recommendations */
        post: operations["recommendations_recommendations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Live
         * @description Process is up — used for Kubernetes liveness (no external deps).
         */
        get: operations["health_live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Ready
         * @description DB reachable — used for Kubernetes readiness.
         */
        get: operations["health_ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/breakers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Breakers
         * @description Circuit breaker states for this process (demo/debug; Grafana uses /metrics).
         */
        get: operations["breakers_breakers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/eval/split": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Eval Split */
        get: operations["eval_split_eval_split_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BrowseFacets */
        BrowseFacets: {
            /** Cities */
            cities: components["schemas"]["FacetValue"][];
            /** Categories */
            categories: components["schemas"]["FacetValue"][];
        };
        /** BrowseResponse */
        BrowseResponse: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Sort */
            sort: string;
            /** Results */
            results: components["schemas"]["ListingResult"][];
            facets?: components["schemas"]["BrowseFacets"] | null;
        };
        /** EvalSplitResponse */
        EvalSplitResponse: {
            /** Cutoff Date */
            cutoff_date: string;
            /** Train Count */
            train_count: number;
            /** Test Count */
            test_count: number;
            /** Notes */
            notes?: string | null;
        };
        /** FacetValue */
        FacetValue: {
            /** Value */
            value: string;
            /** Count */
            count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Listings Count */
            listings_count?: number | null;
        };
        /** ListingDetail */
        ListingDetail: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /** Categories */
            categories: string[];
            /** City */
            city: string | null;
            /** State */
            state: string | null;
            /** Price Level */
            price_level: number | null;
            /** Stars */
            stars: number | null;
            /** Review Count */
            review_count: number;
            /** Primary Image Url */
            primary_image_url?: string | null;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
            /**
             * Attributes
             * @default {}
             */
            attributes: {
                [key: string]: unknown;
            };
            /** Postal Code */
            postal_code?: string | null;
            /**
             * Is Open
             * @default true
             */
            is_open: boolean;
        };
        /** ListingResult */
        ListingResult: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /** Categories */
            categories: string[];
            /** City */
            city: string | null;
            /** State */
            state: string | null;
            /** Price Level */
            price_level: number | null;
            /** Stars */
            stars: number | null;
            /** Review Count */
            review_count: number;
            /** Primary Image Url */
            primary_image_url?: string | null;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
        };
        /**
         * RecommendationRequest
         * @description Seed ids ordered most-recent-first; recency controls centroid weighting.
         */
        RecommendationRequest: {
            /** Seed Listing Ids */
            seed_listing_ids: string[];
            /**
             * Exclude Listing Ids
             * @default []
             */
            exclude_listing_ids: string[];
            /**
             * Limit
             * @default 20
             */
            limit: number;
        };
        /** RecommendationResponse */
        RecommendationResponse: {
            /** Results */
            results: components["schemas"]["ListingResult"][];
            /**
             * Anchors
             * @default {}
             */
            anchors: {
                [key: string]: string;
            };
            /** Seed Count */
            seed_count: number;
            /** Strategy */
            strategy: string;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /** Total */
            total: number;
            /** Results */
            results: components["schemas"]["ListingResult"][];
            /**
             * Mode
             * @default hybrid
             */
            mode: string;
            /** Technique */
            technique?: string | null;
            /** Query Understanding */
            query_understanding?: {
                [key: string]: unknown;
            } | null;
            /** Personalization */
            personalization?: {
                [key: string]: unknown;
            } | null;
        };
        /** SimilarResponse */
        SimilarResponse: {
            /** Listing Id */
            listing_id: string;
            /** Results */
            results: components["schemas"]["ListingResult"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    browse_listings_listings_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                sort?: string;
                /** @description Include city/category facet counts */
                include_facets?: boolean;
                /** @description Max price level (1-4) */
                price_max?: number | null;
                /** @description Category filter */
                category?: string | null;
                /** @description City filter */
                city?: string | null;
                /** @description Minimum star rating */
                min_stars?: number | null;
                /** @description Only listings currently marked open */
                open_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrowseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_listing_listings__listing_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listing_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    similar_listings_listings__listing_id__similar_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                listing_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimilarResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommendations_recommendations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    search_search_get: {
        parameters: {
            query: {
                /** @description Search query */
                q: string;
                limit?: number;
                /** @description Offset (keyword mode only) */
                offset?: number;
                /** @description Retrieval mode */
                mode?: string;
                /** @description Query understanding technique (none, constraints, rewrite, multi_query, hyde) */
                technique?: string | null;
                /** @description User ID for personalized ranking */
                user_id?: string | null;
                /** @description Blend user preference into ranking (requires user_id) */
                personalize?: boolean;
                /** @description Max price level (1-4) */
                price_max?: number | null;
                /** @description Category filter */
                category?: string | null;
                /** @description City filter */
                city?: string | null;
                /** @description Center latitude */
                lat?: number | null;
                /** @description Center longitude */
                lon?: number | null;
                /** @description Geo radius in km */
                radius_km?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    breakers_breakers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
    };
    eval_split_eval_split_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalSplitResponse"];
                };
            };
        };
    };
}
