/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/itinerary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Itinerary */
        post: operations["itinerary_itinerary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BudgetReport */
        BudgetReport: {
            /** Latency Ms */
            latency_ms: number;
            /** Budget Ms */
            budget_ms: number;
            /** Cost Usd Est */
            cost_usd_est: number;
            /** Budget Usd */
            budget_usd: number;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Within Budget */
            within_budget: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Llm Provider */
            llm_provider: string;
            /** Llm Model */
            llm_model: string;
            /** Budget Ms */
            budget_ms: number;
            /** Budget Usd */
            budget_usd: number;
        };
        /** ItineraryRequest */
        ItineraryRequest: {
            /**
             * Query
             * @description Traveler intent, e.g. 'weekend in Portland'
             */
            query: string;
            /**
             * User Id
             * @description Personalizes the underlying search
             */
            user_id?: string | null;
            /**
             * Days
             * @default 1
             */
            days: number;
            /**
             * Top K
             * @description Listings to plan around
             */
            top_k?: number | null;
        };
        /** ItineraryResponse */
        ItineraryResponse: {
            /** Query */
            query: string;
            /** User Id */
            user_id: string | null;
            /** Itinerary */
            itinerary: string;
            /** Listings Used */
            listings_used: components["schemas"]["ListingRef"][];
            /** Llm Provider */
            llm_provider: string;
            /** Llm Model */
            llm_model: string;
            budget: components["schemas"]["BudgetReport"];
        };
        /** ListingRef */
        ListingRef: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** City */
            city?: string | null;
            /**
             * Categories
             * @default []
             */
            categories: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    itinerary_itinerary_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItineraryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItineraryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
