{{- if .Values.appSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "retrieval-engine.fullname" . }}-env-secret
  labels:
    {{- include "retrieval-engine.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $value := .Values.appSecrets }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
